"""
ETF Momentum Rotation - MOMENTUM job (runs once a day, at/just after the open).

The only job that places orders. Four steps, in this order:

  1. Rebalance marking (first session of a new month only): read the plan the
     signal job stored last evening and flag every holding it did NOT retain
     (a rotation - it fell out of the ranking) with marked_for_exit. This is the
     SAME flag the signal job already sets on a trailing-stop breach, so both
     kinds of exit share one mechanism - there is no separate rotate_out list.
  2. Exit loop (every day): market-sell every holding flagged marked_for_exit.
  3. If anything sold, STOP. Nothing else can happen today.
  4. Otherwise, if a rebalance is due, buy the plan's new entries with the cash
     we have, and only then stamp the month as rebalanced.

T+1 settlement is the whole reason for step 3. Dhan settles equity delivery on a
strict T+1 cycle, so cash freed by a same-day SELL cannot buy anything until the
next session. Rather than remember what to buy tomorrow, we just stop - and come
back. What brings us back is that last_rebalanced_month is stamped in step 4 and
nowhere else: until the buys are placed the rebalance is still "due", the signal
job keeps the plan refreshed, and the next session picks up where we left off.
By then every rotation has already been sold, so step 1 finds nothing to mark,
step 2 sells nothing, and step 4 runs. The same mechanism retries a rejected
sell (it stays flagged) and a rejected buy (the month stays unstamped), so no
failure needs its own recovery path.

When a rebalance sells nothing at all - the very first run, or a month whose
holdings were all retained - steps 2 and 3 are no-ops and the buys happen the
same day. That falls out of the ordering; it is not a special case.

Cash gate (bt_v2 L369): new entries are funded only when freed cash (rotation
proceeds + idle cash) > ~0. A runaway winner that leaves ~0 cash means zero new
names are bought - intended behaviour that keeps the book concentrated.

SAFETY: orders are DRY RUN unless live_trading=true. The rebalance only fires when the
stored plan is fresh (generated by the signal job within the last few days), so
a missed signal run never triggers a stale rebalance.
"""
import os
import time
from datetime import datetime

from pymongo import MongoClient
from dotenv import find_dotenv, load_dotenv
from slack_sdk import WebClient
from tamingnifty import connect_dhan as edge
from tamingnifty import utils as util

load_dotenv(find_dotenv())

live_trading = os.environ.get("live_trading", "false").lower() == "true"
CONNECTION_STRING = os.environ.get("CONNECTION_STRING")
user_name = os.environ.get("user_name", "sugam")
MONGO_DB = os.environ.get("MONGO_DB", "Bots")
slack_channel = "etf-momentum-investing"
slack_client = WebClient(token=os.environ.get("slack_token"))

mongo_client = MongoClient(CONNECTION_STRING)
db = mongo_client[MONGO_DB]
universe_coll = db["etf_universe"]
positions = db[f"etf_positions_{user_name}"]   # one doc per position, nothing else
state = db[f"etf_state_{user_name}"]           # the singletons: accounts / meta / plan
orders = db[f"etf_orders_{user_name}"]

# --- strategy parameters ------------------------------------------------------
# The signal job owns the ranking/stop parameters; this job owns only the money.
# Both used to live in an etf_params document in Mongo, which meant the strategy
# could be changed without a code change and without leaving a trace. Constants
# here instead, so git history IS the audit trail.
START_CAPITAL = 400000.0

# the plan must have been generated by the signal job within this many days
PLAN_MAX_AGE_DAYS = 5


def notify(message):
    print(f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {message}", flush=True)
    try:
        util.notify(message=str(message), slack_channel=slack_channel, slack_client=slack_client)
    except Exception as exc:
        print(f"[notify] slack post failed: {exc}", flush=True)


def today():
    return datetime.now().date()


def is_trading_day():
    return today().weekday() < 5      # Mon-Fri only (live)


def parse_date(s):
    return datetime.strptime(str(s)[:10], "%Y-%m-%d").date()


def month_key():
    d = today()
    return f"{d.year:04d}-{d.month:02d}"


# --- universe (read from Mongo; fail loudly if unseeded) ----------------------
def load_universe():
    docs = list(universe_coll.find({"is_park": {"$ne": True}}))
    if not docs:
        notify("MOMENTUM ABORT: etf_universe is empty - seed etf_universe in Mongo first.")
        raise SystemExit(1)
    # secid is the NSE exchange token, which is also Dhan's securityId for cash
    # equity.
    secid_of = {d["symbol"]: d["secid"] for d in docs}
    tsym_of = {d["symbol"]: d["tsym"] for d in docs}
    bucket_of = {d["symbol"]: d["bucket"] for d in docs}
    return secid_of, tsym_of, bucket_of


# --- ledger -------------------------------------------------------------------
# Two collections, one shape each: etf_positions_<user> holds nothing but
# position documents, and the accounts / meta / plan singletons live in
# etf_state_<user>. They used to share a collection, which worked only
# because the singletons happened to have no "status" field and so fell out of
# find({"status": "active"}). That is a trap now that the ledger is DERIVED from
# exactly those queries - one stray status field would silently skew the P&L.
def strip(doc):
    if doc is None:
        return None
    doc = dict(doc)
    doc.pop("_id", None)
    return doc


def compute_accounts():
    """Work the whole ledger out from the position documents themselves.

    Nothing here is incremented. Every figure is derived from the positions, so
    the ledger cannot drift away from them: if a run dies between placing an
    order and updating a running total, the next run simply recomputes the
    truth instead of carrying a wrong number forward for good.

    The arithmetic is the same as the running totals it replaces:
      invested       = capital still tied up in open positions
      total_pnl      = realised P&L, i.e. the sum over closed positions
      unused_balance = start capital, plus what we have made, minus what is
                       currently deployed
      total_balance  = start capital plus what we have made
    """
    start = START_CAPITAL
    active = list(positions.find({"status": "active"}))
    closed = list(positions.find({"status": "closed"}))
    pnls = [float(p.get("pnl") or 0.0) for p in closed]

    invested = round(sum(float(p["capital_deployed"]) for p in active), 2)
    total_pnl = round(sum(pnls), 2)
    return {
        "start_capital": start,
        "total_balance": round(start + total_pnl, 2),
        "unused_balance": round(start + total_pnl - invested, 2),
        "invested": invested,
        "total_trades": len(active) + len(closed),
        "active_trades": len(active),
        "closed_trades": len(closed),
        "winning_trades": sum(1 for p in pnls if p > 0),
        "losing_trades": sum(1 for p in pnls if p < 0),
        "total_pnl": total_pnl,
    }


def save_accounts():
    """Recompute the ledger and store it. Mongo keeps a snapshot for reading;
    the positions remain the single source of truth."""
    acc = compute_accounts()
    state.update_one({"_id": "accounts"}, {"$set": acc}, upsert=True)
    return acc


def get_meta():
    return strip(state.find_one({"_id": "meta"})) or {}


def set_meta(**fields):
    state.update_one({"_id": "meta"}, {"$set": fields}, upsert=True)


def get_plan():
    return strip(state.find_one({"_id": "plan"}))


def active_positions():
    return [strip(p) for p in positions.find({"status": "active"})]


# --- broker (LTP + order placement, DRY-RUN gated) ----------------------------
# Dhan identifies an instrument by securityId, not by trading symbol, so every
# broker call below takes a secid. The tsym is still carried alongside it purely
# because it is readable in Slack messages and in Mongo.
def last_daily_close(conn, secid):
    from datetime import timedelta
    end = datetime.now()
    df = edge.fetch_equity_data(conn, secid, end - timedelta(days=15), end, "day")
    if df is None or len(df) == 0 or "close" not in df.columns:
        return None
    return float(df["close"].iloc[-1])


def ltp(conn, secid):
    try:
        price = edge.get_equity_ltp(conn, secid)
        if price:
            return float(price)
    except Exception:
        pass
    return last_daily_close(conn, secid)


def simulated_order(tsym, side, qty, price):
    # Same shape as a real Dhan order dict, so the code that reads it does not
    # have to care which branch produced it.
    return {
        "orderId": f"DRYRUN-{side}-{tsym}-{datetime.now():%H%M%S}",
        "orderStatus": "DRYRUN", "transactionType": side, "tradingSymbol": tsym,
        "quantity": qty, "filledQty": qty,
        "averageTradedPrice": round(price, 2) if price else 0.0,
        "orderType": "MARKET", "productType": "CNC",
        "message": "dry-run: no order sent to broker",
        "createTime": datetime.now().strftime("%d-%m-%Y %H:%M:%S"),
    }


def place_market(conn, secid, tsym, side, qty):
    """CNC MARKET order for `qty` units of `tsym`. DRY RUN unless live_trading=true."""
    side = side.upper()
    if qty is None or qty <= 0:
        raise ValueError(f"place_market: non-positive qty {qty} for {tsym}")

    if not live_trading:
        return simulated_order(tsym, side, qty, ltp(conn, secid))

    try:
        order = edge.place_equity_order(conn, secid, side, int(qty))
    except Exception as exc:
        # Dhan answers a bad order with an HTTP error, which the library raises.
        # A rejection is an expected outcome here (a deferred buy whose funds have
        # still not settled), and the caller needs a dict it can inspect, so turn
        # the exception back into one rather than letting the whole job die.
        return {"orderStatus": "REJECTED", "message": str(exc)}
    return edge.wait_for_fill(conn, order["orderId"])


def filled(order):
    return order.get("orderStatus") in ("TRADED", "DRYRUN")


def why_failed(order):
    return order.get("omsErrorDescription") or order.get("message") or order.get("orderStatus")


# --- trade actions (accounting invariants preserved exactly from the engine) --
def sell(conn, secid_of, pos, reason):
    """Market-sell a full position, realize P&L and update the ledger."""
    sym, qty = pos["symbol"], pos["quantity"]
    tsym = pos.get("tsym") or sym
    secid = pos.get("secid") or secid_of.get(sym)
    if not secid:
        notify(f"MOMENTUM: SELL SKIPPED {sym} - no secid on the position or in etf_universe.")
        return 0.0
    order = place_market(conn, secid, tsym, "SELL", qty)
    orders.insert_one(dict(order))
    if not filled(order):
        notify(f"MOMENTUM: SELL FAILED {sym} - {why_failed(order)}")
        return 0.0
    avg = float(order["averageTradedPrice"])
    entry = float(pos["entry_price"])
    cap = float(pos["capital_deployed"])
    pnl = round((avg - entry) * qty, 2)
    roi = round(pnl / cap * 100, 2) if cap else 0.0

    positions.update_one(
        {"symbol": sym, "status": "active"},
        {"$set": {"status": "closed", "exit_price": avg, "exit_date": str(today()),
                  "pnl": pnl, "roi": roi, "exit_reason": reason}})
    save_accounts()             # derived from the positions, so recompute AFTER the write
    notify(f"MOMENTUM: SOLD {sym} x{qty} @ {avg:.2f} ({reason}) pnl=Rs{pnl:.0f} roi={roi:.1f}%")
    return round(avg * qty, 2)


def buy(conn, sym, secid, tsym, bucket, alloc):
    """Market-buy `alloc` rupees of `sym`, floored to whole units, and record it."""
    price = ltp(conn, secid)
    if not price or price <= 0:
        notify(f"MOMENTUM: no price for {sym}; skipping buy")
        return None                                     # local skip (not a broker rejection)
    qty = int(alloc / price)                            # whole ETF units only
    if qty <= 0:                                        # skip if the slice buys 0 units
        notify(f"MOMENTUM: alloc Rs{alloc:.0f} buys 0 units of {sym}; skipping")
        return None                                     # local skip (not a broker rejection)
    order = place_market(conn, secid, tsym, "BUY", qty)
    orders.insert_one(dict(order))
    if not filled(order):
        notify(f"MOMENTUM: BUY FAILED {sym} - {why_failed(order)}")
        return False                                    # broker rejected (e.g. funds unsettled)
    avg = float(order["averageTradedPrice"])
    spend = round(avg * qty, 2)

    positions.insert_one({
        "symbol": sym, "secid": secid, "tsym": tsym, "bucket": bucket,
        "entry_price": avg, "quantity": qty, "capital_deployed": spend,
        "entry_date": str(today()), "peak": avg, "status": "active",
        "marked_for_exit": False, "exit_reason": "",
        "ltp": avg, "last_close": avg, "shadow_pnl": 0.0,
        "exit_price": "", "exit_date": "", "pnl": "", "roi": 0.0,
    })
    save_accounts()             # derived from the positions, so recompute AFTER the write
    notify(f"MOMENTUM: BOUGHT {sym} x{qty} @ {avg:.2f} (Rs{spend:.0f})")
    return True


def place_new_entries(conn, secid_of, tsym_of, bucket_of, new_entries, available):
    """Buy `new_entries` now, splitting `available` cash equally across them, each
    slice floored to whole units (matches the engine's equal-weight day snapshot).

    Returns True if all names were placed; False if the broker REJECTED one - the
    caller then stops (the remaining names are skipped). A local skip (no price /
    slice buys 0 units) is not a rejection and does not stop the loop.
    """
    alloc_each = available / len(new_entries)
    for sym in new_entries:
        time.sleep(1)
        secid = secid_of.get(sym)
        if not secid:
            notify(f"MOMENTUM: {sym} is not in etf_universe (no secid); skipping")
            continue
        tsym = tsym_of.get(sym, sym)
        result = buy(conn, sym, secid, tsym, bucket_of.get(sym, ""), alloc_each)
        if result is False:                             # broker rejected the order
            notify(f"MOMENTUM: buy REJECTED - broker declined (e.g. funds unsettled). "
                   f"Skipping the remaining new entries; the month stays unstamped so "
                   f"the next session tries again.")
            return False
    return True


def summary():
    acc = save_accounts()
    holdings = [p["symbol"] for p in active_positions()]
    equity = round(acc["unused_balance"] + acc["invested"], 2)
    notify("MOMENTUM summary | holdings={h} | cash=Rs{c:.0f} | invested=Rs{i:.0f} | "
           "equity=Rs{e:.0f} | realized_pnl=Rs{p:.0f} | W/L={w}/{l}".format(
               h=holdings, c=acc["unused_balance"], i=acc["invested"], e=equity,
               p=acc["total_pnl"], w=acc.get("winning_trades", 0),
               l=acc.get("losing_trades", 0)))


def main():
    if not is_trading_day():
        notify("MOMENTUM: not a trading day - nothing to do.")
        return

    mode = "LIVE" if live_trading else "DRY-RUN"
    secid_of, tsym_of, bucket_of = load_universe()

    conn = edge.login_to_dhan()
    notify(f"MOMENTUM started [{mode}] (NSE)")
    # Dhan only accepts orders from a whitelisted static IP, so print the address
    # this container actually goes out on - it is the first thing to check when
    # orders start getting refused.
    notify(f"MOMENTUM public IP: {util.get_public_ip()}")

    # 1. Rebalance marking. On the first session of a new month, flag every
    #    holding the signal job did NOT retain - it fell out of the ranking, so it
    #    is a rotation. Same marked_for_exit flag the trailing stop uses, so the
    #    exit loop below sells both kinds without knowing the difference.
    #
    #    On the SECOND day of a rebalance there is nothing left to mark: everything
    #    not retained was sold yesterday. The loop finds no rotations, sells
    #    nothing, and falls through to the buys. That is how the two halves of one
    #    rebalance line up across two sessions without any extra bookkeeping.
    current_month = month_key()
    rebalancing = current_month != get_meta().get("last_rebalanced_month")
    plan = get_plan() if rebalancing else None
    if rebalancing and not plan:
        notify(f"MOMENTUM: rebalance DUE for {current_month} but no plan found. "
               f"Skipping rebalance (run the signal job first).")
        rebalancing = False
    elif rebalancing:
        plan_age = (today() - parse_date(plan.get("generated_on", "1970-01-01"))).days
        if plan_age > PLAN_MAX_AGE_DAYS:
            notify(f"MOMENTUM: rebalance DUE for {current_month} but plan is {plan_age} days old "
                   f"(generated_on={plan.get('generated_on')}). Skipping stale plan.")
            rebalancing = False
    if rebalancing:
        retained = set(plan.get("retained") or [])
        rotations = [p for p in active_positions()
                     if p["symbol"] not in retained and not p.get("marked_for_exit")]
        for pos in rotations:
            positions.update_one(
                {"symbol": pos["symbol"], "status": "active"},
                {"$set": {"marked_for_exit": True, "exit_reason": "rebalance"}})
        notify(f"MOMENTUM: rebalancing {current_month} | retain={sorted(retained)} | "
               f"rotate={[p['symbol'] for p in rotations]} | new={plan['new_entries']}")

    # 2. Exit loop, every day: market-sell everything flagged marked_for_exit -
    #    last night's trailing stops plus the rotations just marked. One loop, one
    #    flag, no separate rotate-out list.
    sold_today = []
    for pos in active_positions():
        if pos.get("marked_for_exit"):
            time.sleep(1)
            sell(conn, secid_of, pos, pos.get("exit_reason") or "trailing_stop")
            sold_today.append(pos["symbol"])

    # 3. If we sold anything, stop here. Dhan settles equity delivery T+1, so the
    #    cash those sells just freed is NOT usable until the next session - there
    #    is nothing we could buy with it today. Leaving last_rebalanced_month
    #    unstamped is what brings us back tomorrow: the rebalance is still "due",
    #    the signal job keeps the plan refreshed until it is consumed, and
    #    tomorrow's run finds no rotations left to mark and goes straight to the
    #    buys. A rejected sell stays flagged and is simply retried the same way.
    if sold_today:
        notify(f"MOMENTUM: sold {sold_today} today - T+1 means that cash is not usable "
               f"until the next session, so no entries today.")
        summary()
        return

    # 4. Nothing sold, so whatever cash we hold is settled. If a rebalance is due,
    #    buy the plan's new entries - the names needed to bring the book back to
    #    n_hold - splitting the available cash equally between them. Stamping the
    #    month is the LAST thing we do, so the rebalance counts as done only once
    #    the buys are actually placed.
    if rebalancing:
        new_entries = [s for s in plan["new_entries"]
                       if s not in {p["symbol"] for p in active_positions()}]
        available = compute_accounts()["unused_balance"]
        if not new_entries or available <= 1e-9:
            notify(f"MOMENTUM: no new entries to place (new={new_entries}, cash=Rs{available:.0f}).")
            set_meta(last_rebalanced_month=current_month)
        else:
            notify(f"MOMENTUM: buying {len(new_entries)} new entries (settled cash) | "
                   f"new={new_entries} | cash=Rs{available:.0f}")
            if place_new_entries(conn, secid_of, tsym_of, bucket_of, new_entries, available):
                set_meta(last_rebalanced_month=current_month)

    set_meta(last_momentum_date=str(today()))
    summary()


if __name__ == "__main__":
    main()
