"""
ETF Momentum Rotation - MOMENTUM job (runs once a day, at/just after the open).

The only job that places orders. It does, in this order:

  1. Rebalance marking (first session of a new month only): read the plan the
     signal job stored last evening and flag every holding it did NOT retain
     (a rotation - it fell out of the ranking) with marked_for_exit. This is the
     SAME flag the signal job already sets on a trailing-stop breach, so both
     kinds of exit share one mechanism - there is no separate rotate_out list.
  2. Exit loop (every day): market-sell every holding flagged marked_for_exit -
     the trailing stops flagged by the signal job last night PLUS the rotations
     flagged in step 1. Frees cash (unsettled until tomorrow under T+1).
  3. Deferred entries (any day): if a PREVIOUS rebalance session left a pending
     buy, deploy that snapshot's cash equally across the new entries at today's
     prices, floored to whole units (skip a name if its slice buys 0 units).
  4. New entries (rebalance day only): buy the plan's new entries to refill the
     book toward n_hold. If nothing was sold today the cash is already settled,
     so buy now; if anything was sold today the freed cash won't settle until
     tomorrow, so record the new entries + a freed-cash snapshot as a pending
     buy, to be deployed the NEXT session (see T+1 below).

T+1 settlement: the broker (Dhan) settles equity delivery on a strict T+1
cycle, so the cash freed by a same-day SELL is NOT usable to buy the same day.
The rebalance therefore only defers its new-entry buys when it actually sold
something that day (a stop or a rotation); those deferred buys fill the NEXT
session, matching the entry_lag=1 backtest. When the rebalance sells nothing
(e.g. the very first run, or a month that just redeploys idle settled cash) the
new entries are bought the SAME day. If a deferred next-session buy is rejected
because the funds have still not settled, the job alerts on Slack and skips (the
pending buy is dropped, not retried across further days).

Cash gate (bt_v2 L369): new entries are funded only when freed cash (rotation
proceeds + idle cash) > ~0. A runaway winner that leaves ~0 cash means zero new
names are bought - intended behaviour that keeps the book concentrated.

SAFETY: orders are DRY RUN unless LIVE=1. The rebalance only fires when the
stored plan is fresh (generated by the signal job within the last few days), so
a missed signal run never triggers a stale rebalance.
"""
import os
import time
from datetime import datetime

from pymongo import MongoClient
from dotenv import find_dotenv, load_dotenv
from slack_sdk import WebClient
from tamingnifty import connect_dhan as edge
from tamingnifty import utils as util

load_dotenv(find_dotenv())

LIVE = os.environ.get("LIVE", "0") == "1"
CONNECTION_STRING = os.environ.get("CONNECTION_STRING")
user_name = os.environ.get("user_name", "sugam")
MONGO_DB = os.environ.get("MONGO_DB", "Bots")
slack_channel = "etf-momentum-investing"
slack_client = WebClient(token=os.environ.get("slack_token"))

mongo_client = MongoClient(CONNECTION_STRING)
db = mongo_client[MONGO_DB]
universe_coll = db["etf_universe"]
params_coll = db["etf_params"]
positions = db[f"etf_positions_{user_name}"]
orders = db[f"etf_orders_{user_name}"]

# the plan must have been generated by the signal job within this many days
PLAN_MAX_AGE_DAYS = 5


def notify(message):
    print(f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {message}", flush=True)
    try:
        util.notify(message=str(message), slack_channel=slack_channel, slack_client=slack_client)
    except Exception as exc:
        print(f"[notify] slack post failed: {exc}", flush=True)


def today():
    return datetime.now().date()


def is_trading_day():
    return today().weekday() < 5      # Mon-Fri only (live)


def parse_date(s):
    return datetime.strptime(str(s)[:10], "%Y-%m-%d").date()


def month_key():
    d = today()
    return f"{d.year:04d}-{d.month:02d}"


# --- universe + params (read from Mongo; fail loudly if unseeded) -------------
def load_params():
    doc = params_coll.find_one({"_id": "params"})
    if not doc:
        notify("MOMENTUM ABORT: etf_params is empty - seed etf_params in Mongo first.")
        raise SystemExit(1)
    return doc


def load_universe():
    docs = list(universe_coll.find({"is_park": {"$ne": True}}))
    if not docs:
        notify("MOMENTUM ABORT: etf_universe is empty - seed etf_universe in Mongo first.")
        raise SystemExit(1)
    # secid is the NSE exchange token, which is also Dhan's securityId for cash
    # equity - the same number that was already stored for Definedge, so nothing
    # in etf_universe had to change for the broker move.
    secid_of = {d["symbol"]: d["secid"] for d in docs}
    tsym_of = {d["symbol"]: d["tsym"] for d in docs}
    bucket_of = {d["symbol"]: d["bucket"] for d in docs}
    return secid_of, tsym_of, bucket_of


# --- ledger (accounts / meta / plan live in the positions collection by _id) --
def default_accounts(params):
    cap = float(params["start_capital"])
    return {
        "start_capital": cap, "total_balance": cap, "unused_balance": cap,
        "invested": 0.0, "total_trades": 0, "active_trades": 0,
        "closed_trades": 0, "winning_trades": 0, "losing_trades": 0, "total_pnl": 0.0,
    }


def strip(doc):
    if doc is None:
        return None
    doc = dict(doc)
    doc.pop("_id", None)
    return doc


def get_accounts(params):
    doc = positions.find_one({"_id": "accounts"})
    if doc is None:
        doc = {"_id": "accounts", **default_accounts(params)}
        positions.insert_one(doc)
    return strip(doc)


def save_accounts(acc):
    acc = dict(acc)
    acc.pop("_id", None)
    positions.update_one({"_id": "accounts"}, {"$set": acc}, upsert=True)


def get_meta():
    return strip(positions.find_one({"_id": "meta"})) or {}


def set_meta(**fields):
    positions.update_one({"_id": "meta"}, {"$set": fields}, upsert=True)


def get_plan():
    return strip(positions.find_one({"_id": "plan"}))


def get_pending_buys():
    return strip(positions.find_one({"_id": "pending_buys"}))


def set_pending_buys(month, new_entries, available):
    positions.update_one(
        {"_id": "pending_buys"},
        {"$set": {"month": month, "new_entries": list(new_entries),
                  "available": round(float(available), 2),
                  "created_date": str(today())}},
        upsert=True)


def clear_pending_buys():
    positions.delete_one({"_id": "pending_buys"})


def active_positions():
    return [strip(p) for p in positions.find({"status": "active"})]


# --- broker (LTP + order placement, DRY-RUN gated) ----------------------------
# Dhan identifies an instrument by securityId, not by trading symbol, so every
# broker call below takes a secid. The tsym is still carried alongside it purely
# because it is readable in Slack messages and in Mongo.
def last_daily_close(conn, secid):
    from datetime import timedelta
    end = datetime.now()
    df = edge.fetch_equity_data(conn, secid, end - timedelta(days=15), end, "day")
    if df is None or len(df) == 0 or "close" not in df.columns:
        return None
    return float(df["close"].iloc[-1])


def ltp(conn, secid):
    try:
        price = edge.get_equity_ltp(conn, secid)
        if price:
            return float(price)
    except Exception:
        pass
    return last_daily_close(conn, secid)


def simulated_order(tsym, side, qty, price):
    # Same shape as a real Dhan order dict, so the code that reads it does not
    # have to care which branch produced it.
    return {
        "orderId": f"DRYRUN-{side}-{tsym}-{datetime.now():%H%M%S}",
        "orderStatus": "DRYRUN", "transactionType": side, "tradingSymbol": tsym,
        "quantity": qty, "filledQty": qty,
        "averageTradedPrice": round(price, 2) if price else 0.0,
        "orderType": "MARKET", "productType": "CNC",
        "message": "dry-run: no order sent to broker",
        "createTime": datetime.now().strftime("%d-%m-%Y %H:%M:%S"),
    }


def place_market(conn, secid, tsym, side, qty):
    """CNC MARKET order for `qty` units of `tsym`. DRY RUN unless LIVE=1."""
    side = side.upper()
    if qty is None or qty <= 0:
        raise ValueError(f"place_market: non-positive qty {qty} for {tsym}")

    if not LIVE:
        return simulated_order(tsym, side, qty, ltp(conn, secid))

    try:
        order = edge.place_equity_order(conn, secid, side, int(qty))
    except Exception as exc:
        # Dhan answers a bad order with an HTTP error, which the library raises.
        # A rejection is an expected outcome here (a deferred buy whose funds have
        # still not settled), and the caller needs a dict it can inspect, so turn
        # the exception back into one rather than letting the whole job die.
        return {"orderStatus": "REJECTED", "message": str(exc)}
    return edge.wait_for_fill(conn, order["orderId"])


def filled(order):
    return order.get("orderStatus") in ("TRADED", "DRYRUN")


def why_failed(order):
    return order.get("omsErrorDescription") or order.get("message") or order.get("orderStatus")


# --- trade actions (accounting invariants preserved exactly from the engine) --
def sell(conn, params, secid_of, pos, reason):
    """Market-sell a full position, realize P&L and update the ledger."""
    sym, qty = pos["symbol"], pos["quantity"]
    tsym = pos.get("tsym") or f"{sym}-{params.get('series', 'EQ')}"
    secid = pos.get("secid") or secid_of.get(sym)
    if not secid:
        notify(f"MOMENTUM: SELL SKIPPED {sym} - no secid on the position or in etf_universe.")
        return 0.0
    order = place_market(conn, secid, tsym, "SELL", qty)
    orders.insert_one(dict(order))
    if not filled(order):
        notify(f"MOMENTUM: SELL FAILED {sym} - {why_failed(order)}")
        return 0.0
    avg = float(order["averageTradedPrice"])
    entry = float(pos["entry_price"])
    cap = float(pos["capital_deployed"])
    pnl = round((avg - entry) * qty, 2)
    roi = round(pnl / cap * 100, 2) if cap else 0.0

    acc = get_accounts(params)
    acc["total_balance"] = round(acc["total_balance"] + pnl, 2)
    acc["unused_balance"] = round(acc["unused_balance"] + cap + pnl, 2)
    acc["invested"] = round(acc["invested"] - cap, 2)
    acc["total_pnl"] = round(acc["total_pnl"] + pnl, 2)
    acc["active_trades"] = acc.get("active_trades", 0) - 1
    acc["closed_trades"] = acc.get("closed_trades", 0) + 1
    if pnl > 0:
        acc["winning_trades"] = acc.get("winning_trades", 0) + 1
    elif pnl < 0:
        acc["losing_trades"] = acc.get("losing_trades", 0) + 1
    save_accounts(acc)

    positions.update_one(
        {"symbol": sym, "status": "active"},
        {"$set": {"status": "closed", "exit_price": avg, "exit_date": str(today()),
                  "pnl": pnl, "roi": roi, "exit_reason": reason}})
    notify(f"MOMENTUM: SOLD {sym} x{qty} @ {avg:.2f} ({reason}) pnl=Rs{pnl:.0f} roi={roi:.1f}%")
    return round(avg * qty, 2)


def buy(conn, params, sym, secid, tsym, bucket, alloc):
    """Market-buy `alloc` rupees of `sym`, floored to whole units, and record it."""
    cost = float(params["cost_per_side"])
    price = ltp(conn, secid)
    if not price or price <= 0:
        notify(f"MOMENTUM: no price for {sym}; skipping buy")
        return None                                     # local skip (not a broker rejection)
    qty = int(alloc * (1 - cost) / price)              # whole ETF units only
    if qty <= 0:                                        # skip if the slice buys 0 units
        notify(f"MOMENTUM: alloc Rs{alloc:.0f} buys 0 units of {sym}; skipping")
        return None                                     # local skip (not a broker rejection)
    order = place_market(conn, secid, tsym, "BUY", qty)
    orders.insert_one(dict(order))
    if not filled(order):
        notify(f"MOMENTUM: BUY FAILED {sym} - {why_failed(order)}")
        return False                                    # broker rejected (e.g. funds unsettled)
    avg = float(order["averageTradedPrice"])
    spend = round(avg * qty, 2)

    acc = get_accounts(params)
    acc["unused_balance"] = round(acc["unused_balance"] - spend, 2)
    acc["invested"] = round(acc["invested"] + spend, 2)
    acc["total_trades"] = acc.get("total_trades", 0) + 1
    acc["active_trades"] = acc.get("active_trades", 0) + 1
    save_accounts(acc)

    positions.insert_one({
        "symbol": sym, "secid": secid, "tsym": tsym, "bucket": bucket,
        "entry_price": avg, "quantity": qty, "capital_deployed": spend,
        "entry_date": str(today()), "peak": avg, "status": "active",
        "marked_for_exit": False, "exit_reason": "",
        "ltp": avg, "last_close": avg, "shadow_pnl": 0.0,
        "exit_price": "", "exit_date": "", "pnl": "", "roi": 0.0,
    })
    notify(f"MOMENTUM: BOUGHT {sym} x{qty} @ {avg:.2f} (Rs{spend:.0f})")
    return True


def place_new_entries(conn, params, secid_of, tsym_of, bucket_of, new_entries, available, label):
    """Buy `new_entries` now, splitting `available` cash equally across them, each
    slice floored to whole units (matches the engine's equal-weight day snapshot).

    Returns True if all names were placed; False if the broker REJECTED one - the
    caller then stops (the remaining names are skipped). A local skip (no price /
    slice buys 0 units) is not a rejection and does not stop the loop.
    """
    alloc_each = available / len(new_entries)
    for sym in new_entries:
        time.sleep(1)
        secid = secid_of.get(sym)
        if not secid:
            notify(f"MOMENTUM: {sym} is not in etf_universe (no secid); skipping")
            continue
        tsym = tsym_of.get(sym, f"{sym}-{params.get('series', 'EQ')}")
        result = buy(conn, params, sym, secid, tsym, bucket_of.get(sym, ""), alloc_each)
        if result is False:                             # broker rejected the order
            notify(f"MOMENTUM: buy REJECTED for {label} - broker declined "
                   f"(e.g. funds unsettled). Skipping the remaining new entries.")
            return False
    return True


def deploy_pending_buys(conn, params, secid_of, tsym_of, bucket_of):
    """Deploy the new entries deferred from the previous rebalance session.

    T+1 settlement means the cash freed by the rebalance-day sells is only usable
    the NEXT session. This runs every day; when it finds a pending-buys snapshot
    recorded on an earlier session it deploys that snapshot's cash equally across
    the new entries at today's prices (matching the entry_lag=1 backtest). If the
    broker rejects a buy because the funds have still not settled, it alerts on
    Slack and skips the rest - the pending buys are then dropped, never carried
    across further days.
    """
    pending = get_pending_buys()
    if not pending:
        return
    if str(pending.get("created_date", "")) >= str(today()):
        return                                          # recorded today; funds not settled yet

    new_entries = list(pending.get("new_entries") or [])
    available = float(pending.get("available") or 0.0)
    month = pending.get("month", "")
    if not new_entries or available <= 1e-9:
        clear_pending_buys()
        return

    notify(f"MOMENTUM: deploying deferred entries for {month} (T+1 settled) | "
           f"new={new_entries} | cash_snapshot=Rs{available:.0f}")
    ok = place_new_entries(conn, params, secid_of, tsym_of, bucket_of,
                           new_entries, available, f"{month} deferred (T+1)")
    if not ok:
        notify(f"MOMENTUM: day-2 funds still unsettled for {month} - dropping the pending "
               f"buys (not retried across further days).")
    clear_pending_buys()


def summary(params):
    acc = get_accounts(params)
    holdings = [p["symbol"] for p in active_positions()]
    equity = round(acc["unused_balance"] + acc["invested"], 2)
    notify("MOMENTUM summary | holdings={h} | cash=Rs{c:.0f} | invested=Rs{i:.0f} | "
           "equity=Rs{e:.0f} | realized_pnl=Rs{p:.0f} | W/L={w}/{l}".format(
               h=holdings, c=acc["unused_balance"], i=acc["invested"], e=equity,
               p=acc["total_pnl"], w=acc.get("winning_trades", 0),
               l=acc.get("losing_trades", 0)))


def main():
    if not is_trading_day():
        notify("MOMENTUM: not a trading day - nothing to do.")
        return

    mode = "LIVE" if LIVE else "DRY-RUN"
    params = load_params()
    exchange = params["exchange"]
    secid_of, tsym_of, bucket_of = load_universe()

    conn = edge.login_to_dhan()
    notify(f"MOMENTUM started [{mode}] ({exchange})")
    # Dhan only accepts orders from a whitelisted static IP, so print the address
    # this container actually goes out on - it is the first thing to check when
    # orders start getting refused.
    notify(f"MOMENTUM public IP: {util.get_public_ip()}")

    # 1. On the first session of a new month, decide the rebalance and flag its
    #    rotations. A rotation is any holding the signal job did NOT retain (it
    #    fell out of the ranking). We mark those positions marked_for_exit here so
    #    the SINGLE exit loop below sells them alongside the trailing-stop exits -
    #    one exit mechanism, no separate rotate_out list.
    current_month = month_key()
    meta = get_meta()
    rebalancing = current_month != meta.get("last_rebalanced_month")
    plan = get_plan() if rebalancing else None
    if rebalancing and not plan:
        notify(f"MOMENTUM: rebalance DUE for {current_month} but no plan found. "
               f"Skipping rebalance (run the signal job first).")
        rebalancing = False
    elif rebalancing:
        plan_age = (today() - parse_date(plan.get("generated_on", "1970-01-01"))).days
        if plan_age > PLAN_MAX_AGE_DAYS:
            notify(f"MOMENTUM: rebalance DUE for {current_month} but plan is {plan_age} days old "
                   f"(generated_on={plan.get('generated_on')}). Skipping stale plan.")
            rebalancing = False
    if rebalancing:
        retained = set(plan.get("retained") or [])
        rotations = [p for p in active_positions()
                     if p["symbol"] not in retained and not p.get("marked_for_exit")]
        for pos in rotations:
            positions.update_one(
                {"symbol": pos["symbol"], "status": "active"},
                {"$set": {"marked_for_exit": True, "exit_reason": "rebalance"}})
        notify(f"MOMENTUM: rebalancing {current_month} | retain={sorted(retained)} | "
               f"rotate={[p['symbol'] for p in rotations]} | new={plan['new_entries']}")

    # 2. Single exit loop (every day): market-sell every position flagged
    #    marked_for_exit - the trailing stops flagged by the signal job last night
    #    plus the rotations flagged in step 1. Frees cash (unsettled until tomorrow
    #    under T+1). sold_today gates the new-entry buys below.
    sold_today = False
    for pos in active_positions():
        if pos.get("marked_for_exit"):
            time.sleep(1)
            sell(conn, params, secid_of, pos, pos.get("exit_reason") or "trailing_stop")
            sold_today = True

    # 3. Deploy any new entries deferred from a PREVIOUS rebalance session (their
    #    freed cash has now settled under T+1).
    deploy_pending_buys(conn, params, secid_of, tsym_of, bucket_of)

    # 4. Place this rebalance's new entries. Under T+1 the cash freed by today's
    #    sells does not settle until tomorrow, so:
    #      - sold something today -> DEFER: record a pending-buys snapshot; the next
    #        session's step 3 deploys it once the cash settles.
    #      - sold nothing today   -> the cash is already settled (the very first run,
    #        or a month that only redeploys idle cash), so BUY the new entries now.
    if rebalancing:
        new_entries = list(plan["new_entries"])
        available = get_accounts(params)["unused_balance"]
        if not new_entries or available <= 1e-9:
            notify(f"MOMENTUM: no new entries to place (new={new_entries}, cash=Rs{available:.0f}).")
        elif sold_today:
            set_pending_buys(current_month, new_entries, available)
            notify(f"MOMENTUM: sold today -> deferring {len(new_entries)} new entries to the next "
                   f"session (T+1) | new={new_entries} | cash_snapshot=Rs{available:.0f}")
        else:
            notify(f"MOMENTUM: no exits today -> buying {len(new_entries)} new entries now "
                   f"(settled cash) | new={new_entries} | cash=Rs{available:.0f}")
            place_new_entries(conn, params, secid_of, tsym_of, bucket_of,
                              new_entries, available, f"{current_month} same-day")
        set_meta(last_rebalanced_month=current_month, last_momentum_date=str(today()))
    else:
        set_meta(last_momentum_date=str(today()))

    summary(params)


if __name__ == "__main__":
    main()
