"""
ETF Momentum Rotation - MOMENTUM job (runs once a day, at/just after the open).

The only job that places orders. It does, in this order (mirroring bt_v2.py):

  1. Stop exits (every day): market-sell any holding the signal job flagged
     with marked_for_exit on the previous close. Frees cash.
  2. Monthly rebalance (first session of a new month only): use the plan the
     signal job stored last evening -
        a. sell every non-retained holding (rotate_out) at market,
        b. leave retained winners untouched (let winners run - never resized),
        c. deploy all freed cash equally across the new entries, sized off one
           pre-buy cash snapshot, floored to whole units (skip a name if its
           slice buys 0 units).

Cash gate (bt_v2 L369): new entries are funded only when freed cash
(rotate_out proceeds + idle cash) > ~0. A runaway winner that leaves ~0 cash
means zero new names are bought - intended behaviour that keeps the book
concentrated.

SAFETY: orders are DRY RUN unless LIVE=1. The rebalance only fires when the
stored plan is fresh (generated by the signal job within the last few days), so
a missed signal run never triggers a stale rebalance.
"""
import os
import time
from datetime import datetime

from pymongo import MongoClient
from dotenv import find_dotenv, load_dotenv
from slack_sdk import WebClient
from tamingnifty import connect_definedge as edge
from tamingnifty import utils as util

load_dotenv(find_dotenv())

LIVE = os.environ.get("LIVE", "0") == "1"
CONNECTION_STRING = os.environ.get("CONNECTION_STRING")
user_name = os.environ.get("user_name", "sugam")
MONGO_DB = os.environ.get("MONGO_DB", "Bots")
slack_channel = "etf-momentum-investing"
slack_client = WebClient(token=os.environ.get("slack_token"))

mongo_client = MongoClient(CONNECTION_STRING)
db = mongo_client[MONGO_DB]
universe_coll = db["etf_universe"]
params_coll = db["etf_params"]
positions = db[f"etf_positions_{user_name}"]
orders = db[f"etf_orders_{user_name}"]

# the plan must have been generated by the signal job within this many days
PLAN_MAX_AGE_DAYS = 5


def notify(message):
    print(f"[{datetime.now():%Y-%m-%d %H:%M:%S}] {message}", flush=True)
    try:
        util.notify(message=str(message), slack_channel=slack_channel, slack_client=slack_client)
    except Exception as exc:
        print(f"[notify] slack post failed: {exc}", flush=True)


def today():
    return datetime.now().date()


def is_trading_day():
    return today().weekday() < 5


def parse_date(s):
    return datetime.strptime(str(s)[:10], "%Y-%m-%d").date()


def month_key():
    d = today()
    return f"{d.year:04d}-{d.month:02d}"


# --- universe + params (read from Mongo; fail loudly if unseeded) -------------
def load_params():
    doc = params_coll.find_one({"_id": "params"})
    if not doc:
        notify("MOMENTUM ABORT: etf_params is empty - seed etf_params in Mongo first.")
        raise SystemExit(1)
    return doc


def load_universe():
    docs = list(universe_coll.find({"is_park": {"$ne": True}}))
    if not docs:
        notify("MOMENTUM ABORT: etf_universe is empty - seed etf_universe in Mongo first.")
        raise SystemExit(1)
    tsym_of = {d["symbol"]: d["tsym"] for d in docs}
    bucket_of = {d["symbol"]: d["bucket"] for d in docs}
    return tsym_of, bucket_of


# --- ledger (accounts / meta / plan live in the positions collection by _id) --
def default_accounts(params):
    cap = float(params["start_capital"])
    return {
        "start_capital": cap, "total_balance": cap, "unused_balance": cap,
        "invested": 0.0, "total_trades": 0, "active_trades": 0,
        "closed_trades": 0, "winning_trades": 0, "losing_trades": 0, "total_pnl": 0.0,
    }


def strip(doc):
    if doc is None:
        return None
    doc = dict(doc)
    doc.pop("_id", None)
    return doc


def get_accounts(params):
    doc = positions.find_one({"_id": "accounts"})
    if doc is None:
        doc = {"_id": "accounts", **default_accounts(params)}
        positions.insert_one(doc)
    return strip(doc)


def save_accounts(acc):
    acc = dict(acc)
    acc.pop("_id", None)
    positions.update_one({"_id": "accounts"}, {"$set": acc}, upsert=True)


def get_meta():
    return strip(positions.find_one({"_id": "meta"})) or {}


def set_meta(**fields):
    positions.update_one({"_id": "meta"}, {"$set": fields}, upsert=True)


def get_plan():
    return strip(positions.find_one({"_id": "plan"}))


def get_position(symbol):
    return strip(positions.find_one({"symbol": symbol, "status": "active"}))


def active_positions():
    return [strip(p) for p in positions.find({"status": "active"})]


# --- broker (LTP + order placement, DRY-RUN gated) ----------------------------
def last_daily_close(conn, exchange, tsym):
    from datetime import timedelta
    end = datetime.now()
    df = edge.fetch_historical_data(conn, exchange, tsym, end - timedelta(days=15), end, "day")
    if df is None or len(df) == 0 or "close" not in df.columns:
        return None
    return float(df["close"].iloc[-1])


def ltp(conn, exchange, tsym):
    try:
        price = edge.fetch_ltp(conn, exchange, tsym)
        if price:
            return float(price)
    except Exception:
        pass
    return last_daily_close(conn, exchange, tsym)


def simulated_order(tsym, side, qty, price):
    return {
        "order_id": f"DRYRUN-{side}-{tsym}-{datetime.now():%H%M%S}",
        "order_status": "DRYRUN", "order_type": side, "tradingsymbol": tsym,
        "quantity": qty, "filled_qty": qty,
        "average_traded_price": round(price, 2) if price else 0.0,
        "price_type": "MARKET", "product_type": "CNC",
        "message": "dry-run: no order sent to broker",
        "order_entry_time": datetime.now().strftime("%d-%m-%Y %H:%M:%S"),
    }


def place_market(conn, exchange, tsym, side, qty):
    """CNC MARKET order for `qty` units of `tsym`. DRY RUN unless LIVE=1."""
    side = side.upper()
    if qty is None or qty <= 0:
        raise ValueError(f"place_market: non-positive qty {qty} for {tsym}")

    if not LIVE:
        return simulated_order(tsym, side, qty, ltp(conn, exchange, tsym))

    order_type = conn.ORDER_TYPE_BUY if side == "BUY" else conn.ORDER_TYPE_SELL
    io = edge.IntegrateOrders(conn)
    order = io.place_order(
        exchange=conn.EXCHANGE_TYPE_NSE, order_type=order_type, price=0,
        price_type=conn.PRICE_TYPE_MARKET, product_type=conn.PRODUCT_TYPE_CNC,
        quantity=int(qty), tradingsymbol=tsym,
    )
    order_id = order["order_id"]
    order = io.order(order_id)
    if order.get("order_status") != "COMPLETE":
        time.sleep(2)
        order = io.order(order_id)
    return order


def filled(order):
    return order.get("order_status") in ("COMPLETE", "DRYRUN")


# --- trade actions (accounting invariants preserved exactly from the engine) --
def sell(conn, exchange, params, pos, reason):
    """Market-sell a full position, realize P&L and update the ledger."""
    sym, qty = pos["symbol"], pos["quantity"]
    tsym = pos.get("tsym") or f"{sym}-{params.get('series', 'EQ')}"
    order = place_market(conn, exchange, tsym, "SELL", qty)
    orders.insert_one(dict(order))
    if not filled(order):
        notify(f"MOMENTUM: SELL FAILED {sym} - {order.get('message')}")
        return 0.0
    avg = float(order["average_traded_price"])
    entry = float(pos["entry_price"])
    cap = float(pos["capital_deployed"])
    pnl = round((avg - entry) * qty, 2)
    roi = round(pnl / cap * 100, 2) if cap else 0.0

    acc = get_accounts(params)
    acc["total_balance"] = round(acc["total_balance"] + pnl, 2)
    acc["unused_balance"] = round(acc["unused_balance"] + cap + pnl, 2)
    acc["invested"] = round(acc["invested"] - cap, 2)
    acc["total_pnl"] = round(acc["total_pnl"] + pnl, 2)
    acc["active_trades"] = acc.get("active_trades", 0) - 1
    acc["closed_trades"] = acc.get("closed_trades", 0) + 1
    if pnl > 0:
        acc["winning_trades"] = acc.get("winning_trades", 0) + 1
    elif pnl < 0:
        acc["losing_trades"] = acc.get("losing_trades", 0) + 1
    save_accounts(acc)

    positions.update_one(
        {"symbol": sym, "status": "active"},
        {"$set": {"status": "closed", "exit_price": avg, "exit_date": str(today()),
                  "pnl": pnl, "roi": roi, "exit_reason": reason}})
    notify(f"MOMENTUM: SOLD {sym} x{qty} @ {avg:.2f} ({reason}) pnl=Rs{pnl:.0f} roi={roi:.1f}%")
    return round(avg * qty, 2)


def buy(conn, exchange, params, sym, tsym, bucket, alloc):
    """Market-buy `alloc` rupees of `sym`, floored to whole units, and record it."""
    cost = float(params["cost_per_side"])
    price = ltp(conn, exchange, tsym)
    if not price or price <= 0:
        notify(f"MOMENTUM: no price for {sym}; skipping buy")
        return
    qty = int(alloc * (1 - cost) / price)              # whole ETF units only
    if qty <= 0:                                        # skip if the slice buys 0 units
        notify(f"MOMENTUM: alloc Rs{alloc:.0f} buys 0 units of {sym}; skipping")
        return
    order = place_market(conn, exchange, tsym, "BUY", qty)
    orders.insert_one(dict(order))
    if not filled(order):
        notify(f"MOMENTUM: BUY FAILED {sym} - {order.get('message')}")
        return
    avg = float(order["average_traded_price"])
    spend = round(avg * qty, 2)

    acc = get_accounts(params)
    acc["unused_balance"] = round(acc["unused_balance"] - spend, 2)
    acc["invested"] = round(acc["invested"] + spend, 2)
    acc["total_trades"] = acc.get("total_trades", 0) + 1
    acc["active_trades"] = acc.get("active_trades", 0) + 1
    save_accounts(acc)

    positions.insert_one({
        "symbol": sym, "tsym": tsym, "bucket": bucket,
        "entry_price": avg, "quantity": qty, "capital_deployed": spend,
        "entry_date": str(today()), "peak": avg, "status": "active",
        "marked_for_exit": False, "exit_reason": "",
        "ltp": avg, "last_close": avg, "shadow_pnl": 0.0,
        "exit_price": "", "exit_date": "", "pnl": "", "roi": 0.0,
    })
    notify(f"MOMENTUM: BOUGHT {sym} x{qty} @ {avg:.2f} (Rs{spend:.0f})")


def summary(params):
    acc = get_accounts(params)
    holdings = [p["symbol"] for p in active_positions()]
    equity = round(acc["unused_balance"] + acc["invested"], 2)
    notify("MOMENTUM summary | holdings={h} | cash=Rs{c:.0f} | invested=Rs{i:.0f} | "
           "equity=Rs{e:.0f} | realized_pnl=Rs{p:.0f} | W/L={w}/{l}".format(
               h=holdings, c=acc["unused_balance"], i=acc["invested"], e=equity,
               p=acc["total_pnl"], w=acc.get("winning_trades", 0),
               l=acc.get("losing_trades", 0)))


def main():
    if not is_trading_day():
        notify("MOMENTUM: not a trading day - nothing to do.")
        return

    mode = "LIVE" if LIVE else "DRY-RUN"
    params = load_params()
    exchange = params["exchange"]
    tsym_of, bucket_of = load_universe()

    conn = edge.login_to_integrate()
    notify(f"MOMENTUM started [{mode}] ({exchange})")

    # 1. stop exits flagged by the signal job (every day)
    for pos in active_positions():
        if pos.get("marked_for_exit"):
            time.sleep(1)
            sell(conn, exchange, params, pos, pos.get("exit_reason", "trailing_stop"))

    # 2. monthly rebalance (first session of a new month)
    current_month = month_key()
    meta = get_meta()
    if current_month == meta.get("last_rebalanced_month"):
        notify(f"MOMENTUM: no rebalance due for {current_month}.")
        set_meta(last_momentum_date=str(today()))
        summary(params)
        return

    plan = get_plan()
    if not plan:
        notify(f"MOMENTUM: rebalance DUE for {current_month} but no plan found. "
               f"Skipping (run the signal job first).")
        set_meta(last_momentum_date=str(today()))
        summary(params)
        return

    plan_age = (today() - parse_date(plan.get("generated_on", "1970-01-01"))).days
    if plan_age > PLAN_MAX_AGE_DAYS:
        notify(f"MOMENTUM: rebalance DUE for {current_month} but plan is {plan_age} days old "
               f"(generated_on={plan.get('generated_on')}). Skipping stale plan.")
        set_meta(last_momentum_date=str(today()))
        summary(params)
        return

    notify(f"MOMENTUM: rebalancing {current_month} | retain={plan['retained']} "
           f"rotate_out={plan['rotate_out']} new={plan['new_entries']}")

    # (a) sell rotate_out (non-retained, non-stopped) holdings
    for sym in plan["rotate_out"]:
        pos = get_position(sym)
        if pos:
            time.sleep(1)
            sell(conn, exchange, params, pos, "rebalance")

    # (b) retained winners are deliberately left untouched (let winners run)

    # (c) deploy all freed cash equally across new entries (snapshot-sized)
    new_entries = list(plan["new_entries"])
    available = get_accounts(params)["unused_balance"]
    if new_entries and available > 1e-9:
        alloc_each = available / len(new_entries)      # fixed snapshot, matches engine
        for sym in new_entries:
            time.sleep(1)
            tsym = tsym_of.get(sym, f"{sym}-{params.get('series', 'EQ')}")
            buy(conn, exchange, params, sym, tsym, bucket_of.get(sym, ""), alloc_each)
    else:
        notify(f"MOMENTUM: no new entries funded (new={new_entries}, cash=Rs{available:.0f}).")

    set_meta(last_rebalanced_month=current_month, last_momentum_date=str(today()))
    summary(params)


if __name__ == "__main__":
    main()
